# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.bjlanza.es:
  peer0.org1.bjlanza.es:
  peer0.org2.bjlanza.es:
  peer0.org3.bjlanza.es:

networks:
  bjlanza:
    #driver: bridge
    #ipam:
     #config:
       #- subnet: 10.6.1.0/16

services:
  orderer.bjlanza.es:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.bjlanza.es
    container_name: orderer.bjlanza.es
    networks:
      - bjlanza
  
  peer0.org1.bjlanza.es:
    container_name: peer0.org1.bjlanza.es
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.bjlanza.es
    depends_on:
      - orderer.bjlanza.es
      - couchdb1
    networks:
      - bjlanza

  peer0.org2.bjlanza.es:
    container_name: peer0.org2.bjlanza.es
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.bjlanza.es
    depends_on:
      - orderer.bjlanza.es
      #- couchdb2
    networks:
      - bjlanza

  peer0.org3.bjlanza.es:
    container_name: peer0.org3.bjlanza.es
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org3.bjlanza.es
    depends_on:
      - orderer.bjlanza.es
      #- couchdb3
    networks:
      - bjlanza
  
  cli:
    container_name: cli
    #image: hyperledger/fabric-tools:$IMAGE_TAG
    image: hyperledger/fabric-tools:1.4.2
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.bjlanza.es:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.bjlanza.es/peers/peer0.org1.bjlanza.es/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.bjlanza.es/peers/peer0.org1.bjlanza.es/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.bjlanza.es/peers/peer0.org1.bjlanza.es/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.bjlanza.es/users/Admin@org1.bjlanza.es/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.bjlanza.es
    networks:
      - bjlanza

  cli2:
    container_name: cli2
    #image: hyperledger/fabric-tools:$IMAGE_TAG
    image: hyperledger/fabric-tools:1.4.2
    tty: true
    stdin_open: true
    dns_search: .
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli2
      - CORE_PEER_ADDRESS=peer0.org2.bjlanza.es:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.bjlanza.es/peers/peer0.org2.bjlanza.es/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.bjlanza.es/peers/peer0.org2.bjlanza.es/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.bjlanza.es/peers/peer0.org2.bjlanza.es/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.bjlanza.es/users/Admin@org2.bjlanza.es/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.bjlanza.es
      #- couchdb2
    networks:
      - bjlanza
  
  cli3:
    container_name: cli3
    #image: hyperledger/fabric-tools:$IMAGE_TAG
    image: hyperledger/fabric-tools:1.4.2
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli3
      - CORE_PEER_ADDRESS=peer0.org3.bjlanza.es:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.bjlanza.es/peers/peer0.org3.bjlanza.es/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.bjlanza.es/peers/peer0.org3.bjlanza.es/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.bjlanza.es/peers/peer0.org3.bjlanza.es/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.bjlanza.es/users/Admin@org3.bjlanza.es/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.bjlanza.es
      #- couchdb3
    networks:
      - bjlanza
   
  # - 
  # - Couchdb Databases
  # - 

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
      - DB_URL= http://localhost:5984/member_db
    ports:
      - 5984:5984
    networks:
      - bjlanza
    
  # couchdb2:
  #   container_name: couchdb2
  #   image: hyperledger/fabric-couchdb
  #   environment:
  #     - COUCHDB_USER=
  #     - COUCHDB_PASSWORD=
  #   ports:
  #     - 6984:5984
  #   networks:
  #     - bjlanza

  # couchdb3:
  #   container_name: couchdb3
  #   image: hyperledger/fabric-couchdb
  #   environment:
  #     - COUCHDB_USER=
  #     - COUCHDB_PASSWORD=
  #   ports:
  #     - 7984:5984
  #   networks:
  #     - bjlanza